// Package instrumentation embeds the canonical command-logging bashrc and
// generates the per-session rcfile used in standalone mode.
//
// The embedded file is the single source of truth for shell instrumentation:
// the Dagger base image pipeline and BuildRelease read the same file from
// this directory, container modes source it globally via /etc/bash.bashrc,
// and standalone mode scopes it to workshop terminal sessions only via the
// generated rcfile.
package instrumentation

import (
	_ "embed"
	"os"
	"path/filepath"
)

//go:embed workshop-platform.bashrc
var Bashrc string

// WriteRcfile writes a bash rcfile to <workshopRoot>/workshop-rcfile for use
// with `bash --rcfile` in standalone mode. --rcfile replaces ~/.bashrc, so
// the generated file sources the user's own bashrc first — their aliases,
// prompt, and environment must survive — then adds the logging hook.
func WriteRcfile(workshopRoot string) (string, error) {
	content := "# Generated by workshop-backend — standalone mode terminal rcfile.\n" +
		"[ -f ~/.bashrc ] && . ~/.bashrc\n\n" +
		Bashrc
	path := filepath.Join(workshopRoot, "workshop-rcfile")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return "", err
	}
	return path, nil
}
