apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-ds
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  allowCrossNamespaceImport: true
  datasource:
    jsonData:
      timeInterval: 5s
      tlsSkipVerify: true
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: '1'
    name: loki-ds-name
    type: loki
    url: "http://loki-gateway.grafana.svc.cluster.local/"
    access: proxy
