apiVersion: batch/v1
kind: CronJob
metadata:
  name: rtop
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rtop
            image: rtop:latest
            imagePullPolicy: Never
            #command: ["sleep",  "500h"]
            command: ["rtop",  "-n", "name", "-f", "/root/test.yaml", "admin@server.test3.svc.cluster.local", "admin@server.test.svc.cluster.local"]
          restartPolicy: Never


